### PR TITLE
Add update flag for install package

### PR DESCRIPTION
**Pull request by syossan27**
@bfirsh
It will be able to run `whalebrew install -u` and `whalebrew install --update`.
This flag is force install package.
It is similar to 'go get -u'.

### CODE REVIEW

**Comment by themalkolm** [comment]
Is it same in homebrew? I think it would be great if whalebrew tried to mimic brew commands and flags as much as possible.

**Comment by syossan27** [comment]
hmmm... :-(
Is it OK if you make something with the same function as `brew upgrade`?

**Comment by bfirsh** [comment]
This doesn't do quite what you expect, because it won't pull a new version of the image.

The readme documents how to upgrade a package: https://github.com/bfirsh/whalebrew#upgrade-packages

Perhaps "whalebrew upgrade" could be a shorthand for that.

**Comment by syossan27** [comment]
@bfirsh 
Thank you for your comment :-)
I understood that I was performing the wrong implementation.
Since I want to send a pull request after rewriting the code, I will close this pull request.

**Pull request closed without merging**
