### PR TITLE
Ask permission from user to mount volumes and pass environment variables

### PR DESCRIPTION
**Pull request by nithin-bose**
Ref #23

### CODE REVIEW

**Comment by tjamet** [comment]
Would a `-y` option to force install without prompt message be an idea, thinking about automated scripts for example

**Comment by bfirsh** [comment]
Thanks for contribution @nithin-bose! My laptop is in for repair right now but as soon as I get it back I'll test this out.

@tjamet yep! Great idea. I think we can add in a follow-up PRif need be.

**Comment by nithin-bose** [comment]
@tjamet I agree. I'll add that in another PR once this is merged.

**Comment by bfirsh** [comment]
Made a few tweaks myself - thanks for the contribution @nithin-bose!

**Comment by nithin-bose** [comment]
@bfirsh I would like to get the remove image question when not installing the package. I have almost all the whalebrew images on my system, most of which are not installed 😉

**Pull request merged**
